version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      gomod:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
